### PR TITLE
Supporting MCP27017, button utility

### PR DESCRIPTION
**Pull request by dautushenka**

### CODE REVIEW

**Comment by dautushenka** [comment]
@MrVanosh Could you take a look

**Comment by MrVanosh** [comment]
Thank you for contributing :)

**Comment by MrVanosh** [comment]
I've updated package on npm and renamed it to @mrvanosh/mcp23x17. If you have account on npmjs.com give me your nickname and I will add you as contributor.

**Comment by dautushenka** [comment]
@MrVanosh https://www.npmjs.com/~dautushenka

**Pull request merged**
